INSERT INTO Usuario(id, email, password, rol, activo,descripcion,nombreDeUsuario,generoFav1,generoFav2,foto) VALUES(null, 'test@unlam.edu.ar', 'test', 'ADMIN', true,'Me llamo Tomas y he sido un ávido lector desde que era niño. Mis géneros favoritos son ficcion y deporte','Tomas Pezzano','ficcion','deporte','mifoto2.jpg');
INSERT INTO Libro(id, titulo, autor, editorial, fechaPublicacion, precio, ruta) VALUES
                                                                                    (NULL, 'El Principito', 'Stephen Hawking', 'Planeta', '01-01-1988', 5500, '/spring/images/libros/elprincipito.jpg'),
                                                                                    (NULL, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 'Anaya', '01-01-1605', 8000, '/spring/images/libros/donquijote.jpg'),
                                                                                    (NULL, 'Martín Fierro', 'José Hernández', 'Losada', '01-01-1872', 12000, '/spring/images/libros/martinfierro.jpg'),
                                                                                    (NULL, 'El Fantasma de Canterville', 'Oscar Wilde', 'Alianza Editorial', '01-01-1887', 20000, '/spring/images/libros/elfantasma.jpg'),
                                                                                    (NULL, 'El Jardín Secreto', 'Frances Hodgson Burnett', 'Salamandra', '01-01-1911', 7300, '/spring/images/libros/eljardin.jpg'),
                                                                                    (NULL, 'La Sombra del Viento', 'Carlos Ruiz Zafón', 'Editorial Planeta', '01-01-2001', 25000, '/spring/images/libros/lasombra.jpg'),
                                                                                    (NULL, 'El Chico que Bajo las Estrellas', '', 'Random House', '01-01-2022', 15000, '/spring/images/libros/elchico.jpg'),
                                                                                    (NULL, 'El Alquimista', 'Paulo Coelho', 'Anaya', '01-01-2010', 1000, '/spring/images/libros/elalquimista.jpg');